# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-07-26 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import servicios.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='imagen',
            field=models.FileField(upload_to=servicios.models.directorio_imagenes, verbose_name='Imagen'),
        ),
    ]
