# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-07-26 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import servicios.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20210726_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='contenido',
            field=models.FileField(blank=True, max_length=500, upload_to=servicios.models.directorio_videos, verbose_name='Contenido'),
        ),
    ]
