# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-07-26 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20210726_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='titulo',
            field=models.CharField(blank=True, max_length=30, verbose_name='Titulo'),
        ),
    ]
