# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-19 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=20, verbose_name='Kiosco origen')),
                ('accion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Acci\xf3n realizada')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Fecha del evento')),
            ],
            options={
                'ordering': ('origen',),
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
